# Generated by Django 5.2.7 on 2025-10-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_alter_url_options_urlhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhistory',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shorter.url'),
        ),
    ]
